name: Jest Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Jest tests
        run: node_modules/.bin/jest


      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: List Installed Packages  # Debugging Step
        run: npm list --depth=0

      - name: Check Jest Path  # Debugging Step
        run: which jest || echo "Jest not found"

      - name: Run Jest tests
        run: npx jest
